export const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=a=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))};
const returns=c=>c.slice(1).map((x,i)=>Math.log(x/c[i])).filter(Number.isFinite);
const slopeR2=y=>{const N=y.length;if(N<3)return{trend:0,r2:0};const mx=(N-1)/2,my=mean(y);let cov=0,vx=0,vy=0;for(let i=0;i<N;i++){const dx=i-mx,dy=y[i]-my;cov+=dx*dy;vx+=dx*dx;vy+=dy*dy}return{trend:vx?cov/vx:0,r2:vx&&vy?cov*cov/(vx*vy):0}};
const pctRank=(arr,v)=>{const a=arr.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return .5;let i=0;while(i<a.length&&a[i]<=v)i++;return i/a.length};
export function universe(exchange,tickers,books){const T=new Map(tickers.map(x=>[x.symbol,x])),B=new Map(books.map(x=>[x.symbol,x]));return (exchange.symbols||[]).flatMap(s=>{if(s.status!=='TRADING'||s.isSpotTradingAllowed===false)return[];const t=T.get(s.symbol),b=B.get(s.symbol)||{};if(!t)return[];const bid=n(b.bidPrice||t.bidPrice),ask=n(b.askPrice||t.askPrice);return[{symbol:s.symbol,base:s.baseAsset,quote:s.quoteAsset,last:n(t.lastPrice),change24:n(t.priceChangePercent)/100,quoteVolume:n(t.quoteVolume),trades:n(t.count),spreadBps:bid&&ask?(ask-bid)/((ask+bid)/2)*10000:null}]})}
export function broadRank(rows){const lv=rows.map(x=>Math.log10(Math.max(1,x.quoteVolume))),lt=rows.map(x=>Math.log10(Math.max(1,x.trades))),mv=rows.map(x=>Math.abs(x.change24)),sp=rows.map(x=>Number.isFinite(x.spreadBps)?x.spreadBps:1e6);return rows.map(x=>{const f={liquidity:pctRank(lv,Math.log10(Math.max(1,x.quoteVolume))),activity:pctRank(lt,Math.log10(Math.max(1,x.trades))),movement:pctRank(mv,Math.abs(x.change24)),tightness:1-pctRank(sp,Number.isFinite(x.spreadBps)?x.spreadBps:1e6)};return{...x,factors:f,broadScore:.36*f.liquidity+.24*f.activity+.22*f.movement+.18*f.tightness}}).sort((a,b)=>b.broadScore-a.broadScore)}
export function candleMetrics(rows){const c=rows.map(r=>({o:n(r[1]),h:n(r[2]),l:n(r[3]),c:n(r[4]),q:n(r[7]),tr:n(r[8]),tb:n(r[10])})).filter(x=>x.c>0),cl=c.map(x=>x.c),re=returns(cl),last=cl.at(-1)||0,w=cl.slice(-48),m=mean(w),s=sd(w),sr=slopeR2(cl.slice(-96).map(Math.log)),vol=mean(c.slice(-12).map(x=>x.q)),prev=mean(c.slice(-48,-12).map(x=>x.q)),tr=mean(c.slice(-12).map(x=>x.tr)),ptr=mean(c.slice(-48,-12).map(x=>x.tr));let peak=0,dd=0;for(const x of cl.slice(-96)){peak=Math.max(peak,x);if(peak)dd=Math.min(dd,x/peak-1)};const hi=Math.max(...w,last),lo=Math.min(...w,last);return{last,momentum24:cl.length>24?last/cl.at(-25)-1:0,realisedVol:sd(re.slice(-48))*Math.sqrt(48),trend:sr.trend,trendR2:sr.r2,z:s?(last-m)/s:0,breakout:hi>lo?(last-lo)/(hi-lo):.5,volumeAccel:prev?vol/prev:1,tradeAccel:ptr?tr/ptr:1,takerBuy:mean(c.slice(-24).map(x=>x.q?x.tb/x.q:.5)),maxDrawdown:dd}}
export function depthMetrics(d,last){const bids=(d.bids||[]).map(([p,q])=>[n(p),n(q)]),asks=(d.asks||[]).map(([p,q])=>[n(p),n(q)]),bn=bids.reduce((s,[p,q])=>s+p*q,0),an=asks.reduce((s,[p,q])=>s+p*q,0);const impact=(levels,buy)=>{let rem=1000,b=0,q=0;for(const[p,z]of levels){const take=Math.min(rem,p*z);b+=take/p;q+=take;rem-=take;if(rem<=0)break}if(rem>10||!b||!last)return null;const avg=q/b;return(buy?avg/last-1:1-avg/last)*10000};return{imbalance:bn+an?(bn-an)/(bn+an):0,buyImpactBps:impact(asks,true),sellImpactBps:impact(bids,false)}}
export function deepScore(x,tf,depth={}){const m5=tf['5m'],m15=tf['15m'],h1=tf['1h'],h4=tf['4h'];const trend=[m5,m15,h1,h4].map((m,i)=>Math.tanh(m.trend*[220,120,45,18][i])).reduce((a,b)=>a+b,0)/4;const momentum=[m5,m15,h1].map((m,i)=>Math.tanh(m.momentum24*[8,5,3][i])).reduce((a,b)=>a+b,0)/3;const volShock=Math.tanh(Math.log(Math.max(.1,m5.volumeAccel)));const flow=(m5.takerBuy-.5)*2,book=depth.imbalance||0,breakout=(m15.breakout-.5)*2;const risk=Math.min(1,m5.realisedVol*3)+Math.min(1,-h1.maxDrawdown*2);const raw=.22*trend+.19*momentum+.14*volShock+.12*flow+.12*book+.09*breakout+.08*(x.factors?.liquidity||.5)-.08*risk;return{score:raw,confidence:Math.max(.01,Math.min(.99,.5+raw/2)),direction:raw>.12?'LONG_BIAS':raw<-.12?'AVOID':'NEUTRAL',components:{trend,momentum,volShock,flow,book,breakout,risk}}}
